spring.application.name=restaurant-system

#------CONFIGURAÇOES DO BANCO DE DADOS------
#
spring.datasource.url=jdbc:postgresql://ep-crimson-cloud-acmbg9qw-pooler.sa-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DK0u8FfiaGCS

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true